
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: 'geik/vuepress:1.0.0'

steps:

- script: |
    pwd
    ls -aR $(Build.Repository.LocalPath)
    pwsh /build-sidebar.json.ps1 $(Build.Repository.LocalPath)/content
    
  displayName: 'Build the vuepress site from markdown files'

