
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: 'geik/vuepress:1.0.0'

steps:

- script: |
    pwd

  displayName: 'Show me the build environment'

- script: |
    pwsh /build-sidebar.json.ps1 $(Build.Repository.LocalPath)/content
    cat $(Build.Repository.LocalPath)/content/.vuepress/sidebar.json
    
  displayName: 'Generate the sidebar based on the markdown files'

- script: |
    vuepress build $(Build.Repository.LocalPath)/content
    
  displayName: 'Build the vuepress site from markdown files'  

- script: |
    yum update -y
    yum install -y lftp
    yum install -y sshpass
    sshpass -p $env:SFTP_PASSWORD ssh eikens.com@ssh.eikens.com
    lftp -u eikens.com,$env:SFTP_PASSWORD ssh.eikens.com -e "ls; bye"
    
  displayName: 'Copy the generated vuepress site to the target location'
  env:
    SFTP_PASSWORD: $(SFTP_PASSWORD)
