
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: Let's tell something abount the environment
  displayName: 'Show environment'
- script: |
    pwd
    ls -aR .
    ls -aR $(Build.Repository.LocalPath)

- task: Docker@0

  displayName: 'Run the vuepress image and build the website from markdown files'

  inputs:

    containerregistrytype: 'Container Registry'

    dockerRegistryConnection: 'Docker Hub Geik'

    action: 'Run an image'

    imageName: 'geik/vuepress:1.0.0'

    containerCommand: 'pwsh /build-sidebar.json.ps1 content'

    detached: false
