
trigger:
- master

pool:
  vmImage: 'index.docker.io/v1/geik/vuepress:1.0.0'

steps:

- task: Docker@0

  displayName: 'Run the vuepress image and build the website from markdown'

  inputs:

    containerregistrytype: 'Container Registry'

    dockerRegistryConnection: 'Docker Hub Geik'

    action: 'Run an image'

    imageName: 'vuepress:1.0.0'

    containerCommand: 'pwsh /build-sidebar.json.ps1 ./content'

    detached: false
