
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@0

  displayName: 'Run the vuepress image and build the website from markdown'

  inputs:

    containerregistrytype: 'Container Registry'

    dockerRegistryConnection: 'Docker Hub Geik'

    action: 'Run an image'

    imageName: 'geik/vuepress:1.0.0'

    containerCommand: 'pwsh /build-sidebar.json.ps1 $(Build.Repository.LocalPath)/content'

    detached: false
